### ISSUE TITLE
TypeScript @types

### ISSUE THREAD

**Issue by StevenTCramer** [EdgeApp/yaob#5]
I know this is using flow but do you have Typescript Definition files?

**Comment by swansontec** [comment]
No, but I do have a [branch](https://github.com/EdgeApp/yaob/tree/typescript) that started porting yaob to Typescript. The idea was to write the library in Typescript, and then generate Flow types using [flowgen](https://www.npmjs.com/package/flowgen). The plan failed when flowgen turned out not to be capable enough to handle the weird types we have.

Maybe we could grab the types out of this branch and assemble them into a .d.ts file to include with the library.

**Comment by knap1930** [comment]
+1 would love to see @types support
Was planning on giving a yaob a shot (found this comment, https://github.com/react-native-community/react-native-webview/issues/66#issuecomment-441855460)

**Comment by swansontec** [comment]
I have a PR to fix this, #10, but I don't have a solid test case at this point. None of my own yaob-based projects are written in Typescript. Once I can get it tested somehow, I'll go ahead and merge.
